version: '3.9'

services:
  db:
    container_name: postgresql
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ab_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: {}
  