version: '3.9'

services:
  db:
    container_name: postgresql-ab
    image: postgres:16-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ab_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      ab-network:
        ipv4_address: 172.36.0.2
  
  pgadmin:
    container_name: pgadmin-ab
    image: dpage/pgadmin4:8.9
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: app.apadrinhabrasil@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres #7x7m1g3a
    networks:
      ab-network:
        ipv4_address: 172.36.0.3

networks:
  ab-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.36.0.0/16

volumes:
  pgdata: {}
  